# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        media.storage:
            adapter: 'aws'
            options:
                client: 'media_storage_s3'
                bucket: '%env(OVH_BUCKET_NAME)%'
                prefix: 'medias'
                streamReads: true
