framework:
  messenger:
    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          table_name: "messenger_messages"
        retry_strategy:
          max_retries: 3
          # milliseconds delay
          delay: 300000
          # causes the delay to be higher before each retry
          # e.g. 1 second delay, 2 seconds, 4 seconds
          multiplier: 2

    routing:
      # Route your messages to the transports
      'App\Message\FileUploadFromUrlMessage': async

when@test:
  framework:
    messenger:
      transports:
        async: "in-memory://"
