framework:
  messenger:
    buses:
      messenger.bus.default:
          middleware:
                - 'App\Messenger\RetryCountArgumentAdderMiddleware'
    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          table_name: "messenger_messages"
        retry_strategy:
          max_retries: "%env(int:MAX_UPLOAD_RETRIES)%"
          # milliseconds delay
          delay: 1000
          # causes the delay to be higher before each retry
          # e.g. 1 second delay, 2 seconds, 4 seconds
          multiplier: 2

    routing:
      # Route your messages to the transports
      'App\Message\FileUploadFromUrlMessage': async

when@test:
  framework:
    messenger:
      transports:
        async: "in-memory://"
