nelmio_api_doc:
  documentation:
    info:
      title: Aristote
      description: Aristote's API documentation
      version: 1.0.0
    components:
      securitySchemes:
        oauth2:
          type: oauth2
          flows:
            clientCredentials:
              tokenUrl: /api/token
              scopes:
                scope_default: Default scope
                scope_client: Client scope
                scope_processing_worker: Processing worker scope
                scope_transcription_worker: Transcription worker scope
                scope_evaluation_worker: Evaluation worker scope
    # Send OAuth2 authentication on all routes in the documentation
    security:
      - oauth2: []
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$|/doc.json) # Accepts routes under /api except /api/doc and /api/doc.json
