services:
  admin.administrator:
    class: App\Admin\AdministratorAdmin
    tags:
      - name: sonata.admin
        model_class: App\Entity\Administrator
        manager_type: orm
        group: Utilisateurs
        label: Administrateurs
    calls:
      - [setUserManager, ['@App\Service\UserManager']]
    public: true

  admin.api_client:
    class: App\Admin\ApiClientAdmin
    tags:
      - name: sonata.admin
        model_class: App\Entity\ApiClient
        manager_type: orm
        group: Utilisateurs
        label: Clients API
    calls:
      - [setApiClientManager, ['@App\Service\ApiClientManager']]
    public: true

  admin.ai_model:
    class: App\Admin\AiModelAdmin
    tags:
      - name: sonata.admin
        model_class: App\Entity\AiModel
        manager_type: orm
        group: Utilisateurs
        label: Modèles IA
    public: true

  admin.infrastructure:
    class: App\Admin\InfrastructureAdmin
    tags:
      - name: sonata.admin
        model_class: App\Entity\Infrastructure
        manager_type: orm
        group: Utilisateurs
        label: Infrastructures
    public: true

  admin.enrichment:
    class: App\Admin\EnrichmentAdmin
    tags:
      - name: sonata.admin
        model_class: App\Entity\Enrichment
        manager_type: orm
        group: Enrichissements
        label: Enrichissements
    public: true