# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
imports:
  - resource: admin.yaml

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\EventListener\IncomingRequestListener:
    tags:
      - name: "kernel.event_listener"
        event: "kernel.request"

  App\EventListener\LastLoginListener:
    tags:
      - name: "kernel.event_listener"
        event: "security.interactive_login"

  App\EventListener\LastTokenRequestListener:
    tags:
      - name: "kernel.event_listener"
        event: "league.oauth2_server.event.token_request_resolve"

  League\OAuth2\Server\Repositories\ClientRepositoryInterface:
    class: App\Service\ApiClientManager

  media_storage_s3:
    class: Aws\S3\S3Client
    factory: [ Aws\S3\S3Client, 'factory' ]
    arguments:
      - version: '2006-03-01'
        region: '%env(OVH_REGION)%'
        credentials:
          key: '%env(OVH_ACCESS_KEY)%'
          secret: '%env(OVH_SECRET_KEY)%'
        endpoint: '%env(OVH_ENDPOINT_URL)%'

  Aws\S3\S3Client: '@media_storage_s3'

  app.service.video_upload_service:
    class: App\Service\VideoUploadService
    arguments:
      $baseDirectory: '%env(APP_ENV)%/videos/'
      $bucketName: '%env(OVH_BUCKET_NAME)%'
      $linkExpirationInMinutes: '%env(S3_LINK_EXPIRATION_IN_MINUTES)%'

  App\Service\VideoUploadService: '@app.service.video_upload_service'

  app.transcription_worker:
    class: App\Service\EnrichmentWorkerService
    arguments:
      $clientId: "%env(TRANSCRIPTION_WORKER_CLIENT_ID)%"
      $clientSecret: "%env(TRANSCRIPTION_WORKER_SECRET)%"
      $uriPrefix: "%env(URI_PREFIX)%"

  app.ai_enrichment_worker:
    class: App\Service\EnrichmentWorkerService
    arguments:
      $clientId: "%env(AI_ENRICHMENT_WORKER_CLIENT_ID)%"
      $clientSecret: "%env(AI_ENRICHMENT_WORKER_SECRET)%"
      $uriPrefix: "%env(URI_PREFIX)%"
  
  App\Command\TranscribingWorkerCommand:
    arguments:
      $enrichmentWorkerService: '@app.transcription_worker'
  
  App\Command\AiEnrichmentWorkerCommand:
    arguments:
      $enrichmentWorkerService: '@app.ai_enrichment_worker'
  
  App\Controller\Api\TranscribingWorkerController:
    arguments:
      $transcriptionWorkerTimeoutInMinutes: "%env(TRANSCRIPTION_WORKER_TIMEOUT_IN_MINUTES)%"

  App\Controller\Api\AiEnrichmentsWorkerController:
    arguments:
      $aiEnrichmentWorkerTimeoutInMinutes: "%env(AI_ENRICHMENT_WORKER_TIMEOUT_IN_MINUTES)%"
